let bone = document.querySelector('.bone');
let btwo = document.querySelector('.btwo');
let bthree = document.querySelector('.bthree');
let bfour = document.querySelector('.bfour');
let bfive = document.querySelector('.bfive');
let bsix = document.querySelector('.bsix');
let bseven = document.querySelector('.bseven');
let beight = document.querySelector('.beight');
let bnine = document.querySelector('.bnine');
let bten = document.querySelector('.bten');
let one = document.querySelector('#one');
let two = document.querySelector('#two');
let three = document.querySelector('#three');
let four = document.querySelector('#four');
let five = document.querySelector('#five');

one.addEventListener('click', () => {
    one.style.backgroundColor = 'transparent';
    one.style.textShadow = 'none';
    one.style.color = 'black';
    two.style.backgroundColor = 'rgb(241, 180, 48)';
    two.style.textShadow = '1px 2px 3px black';
    two.style.color = 'white';
    three.style.backgroundColor = 'rgb(241, 180, 48)';
    three.style.textShadow = '1px 2px 3px black';
    three.style.color = 'white';
    four.style.backgroundColor = 'rgb(241, 180, 48)';
    four.style.textShadow = '1px 2px 3px black';
    four.style.color = 'white';
    five.style.backgroundColor = 'rgb(241, 180, 48)';
    five.style.textShadow = '1px 2px 3px black';
    five.style.color = 'white';
    bone.classList.add('aone');
    btwo.classList.add('aone');
    bone.classList.remove('aones');
    btwo.classList.remove('aones');
    bthree.classList.add('aone');
    bthree.classList.remove('aones');
    bfour.classList.add('aone');
    bfive.classList.add('aone');
    bfour.classList.remove('aones');
    bfive.classList.remove('aones');
    bsix.classList.add('aone');
    bsix.classList.remove('aones');
    bseven.classList.add('aone');
    beight.classList.add('aone');
    bnine.classList.add('aone');
    bten.classList.add('aone');
    bseven.classList.remove('aones');
    beight.classList.remove('aones');
    bnine.classList.remove('aones');
    bten.classList.remove('aones');
});

two.addEventListener("click", () => {
    two.style.backgroundColor = 'transparent';
    two.style.textShadow = 'none';
    two.style.color = 'black';
    one.style.backgroundColor = 'rgb(241, 180, 48)';
    one.style.textShadow = '1px 2px 3px black';
    one.style.color = 'white';
    three.style.backgroundColor = 'rgb(241, 180, 48)';
    three.style.textShadow = '1px 2px 3px black';
    three.style.color = 'white';
    four.style.backgroundColor = 'rgb(241, 180, 48)';
    four.style.textShadow = '1px 2px 3px black';
    four.style.color = 'white';
    five.style.backgroundColor = 'rgb(241, 180, 48)';
    five.style.textShadow = '1px 2px 3px black';
    five.style.color = 'white';
    bone.classList.add('aone');
    btwo.classList.add('aone');
    bone.classList.remove('aones');
    btwo.classList.remove('aones');
    bthree.classList.add('aones');
    bfour.classList.add('aones');
    bfive.classList.add('aones');
    bsix.classList.add('aone');
    bsix.classList.remove('aones');
    bseven.classList.add('aones');
    beight.classList.add('aones');
    bnine.classList.add('aones');
    bten.classList.add('aones');
});

three.addEventListener('click', () => {
    three.style.backgroundColor = 'transparent';
    three.style.textShadow = 'none';
    three.style.color = 'black';
    one.style.backgroundColor = 'rgb(241, 180, 48)';
    one.style.textShadow = '1px 2px 3px black';
    one.style.color = 'white';
    two.style.backgroundColor = 'rgb(241, 180, 48)';
    two.style.textShadow = '1px 2px 3px black';
    two.style.color = 'white';
    four.style.backgroundColor = 'rgb(241, 180, 48)';
    four.style.textShadow = '1px 2px 3px black';
    four.style.color = 'white';
    five.style.backgroundColor = 'rgb(241, 180, 48)';
    five.style.textShadow = '1px 2px 3px black';
    five.style.color = 'white';
    three.style.backgroundColor = 'transparent';
    three.style.textShadow = 'none';
    three.style.color = 'black';
    bthree.classList.remove('aones');
    bfour.classList.remove('aones');
    bseven.classList.remove('aones');
    bone.classList.add('aones');
    btwo.classList.add('aones');
    bsix.classList.add('aones');
    bfive.classList.add('aones');
    beight.classList.add('aones');
    bnine.classList.add('aones');
    bten.classList.add('aones');
});

four.addEventListener('click', () => {
    four.style.backgroundColor = 'transparent';
    four.style.textShadow = 'none';
    four.style.color = 'black';
    one.style.backgroundColor = 'rgb(241, 180, 48)';
    one.style.textShadow = '1px 2px 3px black';
    one.style.color = 'white';
    three.style.backgroundColor = 'rgb(241, 180, 48)';
    three.style.textShadow = '1px 2px 3px black';
    three.style.color = 'white';
    two.style.backgroundColor = 'rgb(241, 180, 48)';
    two.style.textShadow = '1px 2px 3px black';
    two.style.color = 'white';
    five.style.backgroundColor = 'rgb(241, 180, 48)';
    five.style.textShadow = '1px 2px 3px black';
    five.style.color = 'white';
    four.style.backgroundColor = 'transparent';
    four.style.textShadow = 'none';
    four.style.color = 'black';
    bnine.classList.remove('aones');
    bten.classList.remove('aones');
    bfive.classList.remove('aones');
    bone.classList.add('aones');
    btwo.classList.add('aones');
    bthree.classList.add('aones');
    bfour.classList.add('aones');
    bsix.classList.add('aones');
    bseven.classList.add('aones');
    beight.classList.add('aones');
});

five.addEventListener('click', () => {
    five.style.backgroundColor = 'transparent';
    five.style.textShadow = 'none';
    five.style.color = 'black';
    one.style.backgroundColor = 'rgb(241, 180, 48)';
    one.style.textShadow = '1px 2px 3px black';
    one.style.color = 'white';
    three.style.backgroundColor = 'rgb(241, 180, 48)';
    three.style.textShadow = '1px 2px 3px black';
    three.style.color = 'white';
    four.style.backgroundColor = 'rgb(241, 180, 48)';
    four.style.textShadow = '1px 2px 3px black';
    four.style.color = 'white';
    two.style.backgroundColor = 'rgb(241, 180, 48)';
    two.style.textShadow = '1px 2px 3px black';
    two.style.color = 'white';
    beight.classList.remove('aones');
    btwo.classList.remove('aones');
    bseven.classList.remove('aones');
    bone.classList.add('aones');
    bthree.classList.add('aones');
    bfour.classList.add('aones');
    bfive.classList.add('aones');
    bsix.classList.add('aones');
    bnine.classList.add('aones');
    bten.classList.add('aones');
});